all:
  sfDoctrineEditableComponentPlugin:
    admin_credential: editable_content_admin
    assets_web_root: /sfDoctrineEditableComponentPlugin
    component_css_class_name: sfEditableComponent
    default_content: This is a placeholder. In editing mode, double-click me to edit.
    load_ckeditor:   true
    load_facebox:    true
    load_jquery:     true
    use_rich_editor: true